apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: mongodb-keyvault
  namespace: nodejs-app

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    useWorkloadIdentity: "true"

    # User Assigned Managed Identity Client ID
    clientID: "<UAMI_CLIENT_ID>"

    # Azure Key Vault
    keyvaultName: "<KEY_VAULT_NAME>"
    tenantId: "<AZURE_TENANT_ID>"

    objects: |
      array:
        - |
          objectName: db-host
          objectType: secret

        - |
          objectName: db-name
          objectType: secret

        - |
          objectName: db-username
          objectType: secret

        - |
          objectName: db-password
          objectType: secret

  # Sync Key Vault secrets into a Kubernetes Secret
  secretObjects:
    - secretName: mongodb-secrets
      type: Opaque

      data:
        - objectName: db-host
          key: db-host

        - objectName: db-name
          key: db-name

        - objectName: db-username
          key: db-username

        - objectName: db-password
          key: db-password